# Generated by Django 5.0.6 on 2024-07-10 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "حساب کاربری",
                "verbose_name_plural": "حساب های کاربری",
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="fathers_name",
            field=models.CharField(max_length=50, verbose_name="نام پدر"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/profiles",
                verbose_name="عکس کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="melicode",
            field=models.CharField(max_length=10, verbose_name="کد ملی"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
