# Generated by Django 5.0.6 on 2024-06-27 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_new"),
    ]

    operations = [
        migrations.DeleteModel(
            name="New",
        ),
    ]
