# Generated by Django 5.0.6 on 2024-06-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_category_slug_alter_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(related_name="articles", to="blog.category"),
        ),
    ]
