# Generated by Django 5.0.6 on 2024-07-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_contactus_created_alter_contactus_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="age",
            field=models.IntegerField(default=0),
        ),
    ]
