# Generated by Django 5.0.6 on 2024-07-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_contactus_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/articles"),
        ),
    ]
