# Generated by Django 5.0.6 on 2024-07-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0012_alter_article_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
