# Generated by Django 5.0.6 on 2024-07-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_alter_comment_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
