# Generated by Django 5.0.6 on 2024-07-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_alter_comment_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(null=True),
        ),
    ]
