# Generated by Django 5.0.6 on 2024-07-10 15:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0017_article_pub_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ("-created",),
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ("-created",),
                "verbose_name": "کامنت",
                "verbose_name_plural": "کامنت ها",
            },
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "تماس با ما", "verbose_name_plural": "تماس با ما"},
        ),
        migrations.AlterField(
            model_name="article",
            name="auther",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="نویسنده",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="body",
            field=models.TextField(verbose_name="بدنه"),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(
                related_name="articles", to="blog.category", verbose_name="دسته بندی"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="images/articles", verbose_name="عکس"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 10, 15, 3, 27, 318544, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=50, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=100, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.article",
                verbose_name="مقاله",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نویسنده",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(verbose_name="بدنه"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="blog.comment",
                verbose_name="ریپلای",
            ),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="age",
            field=models.IntegerField(default=0, verbose_name="سن"),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="ایمیل"),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="text",
            field=models.TextField(verbose_name="پیام"),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="title",
            field=models.CharField(max_length=100, null=True, verbose_name="عنوان"),
        ),
    ]
