# Generated by Django 5.0.6 on 2024-07-10 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0018_alter_article_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/articles", verbose_name="عکس"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 10, 15, 23, 35, 891772, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ",
            ),
        ),
    ]
