# Generated by Django 5.0.6 on 2024-07-12 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0020_alter_comment_options_alter_article_pub_date_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 12, 9, 13, 51, 212941, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ",
            ),
        ),
    ]
