# Generated by Django 5.0.6 on 2024-07-23 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0021_alter_article_pub_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactus",
            name="age",
        ),
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 23, 14, 58, 32, 970880, tzinfo=datetime.timezone.utc
                ),
                verbose_name="تاریخ",
            ),
        ),
    ]
